// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPTwyhIRqfouFIrcMEQgt8GZBMfLSmxSU',
    appId: '1:484902349205:web:a778f1abf46525cb7b6e9c',
    messagingSenderId: '484902349205',
    projectId: 'afyakit-api',
    authDomain: 'afyakit-api.firebaseapp.com',
    storageBucket: 'afyakit-api.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwLD7S4anMVDJh2TA9MCWAFCaaWa8wACg',
    appId: '1:484902349205:android:d2f9e94e1bf70ddf7b6e9c',
    messagingSenderId: '484902349205',
    projectId: 'afyakit-api',
    storageBucket: 'afyakit-api.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPTwyhIRqfouFIrcMEQgt8GZBMfLSmxSU',
    appId: '1:484902349205:web:f6420c9a3d184e687b6e9c',
    messagingSenderId: '484902349205',
    projectId: 'afyakit-api',
    authDomain: 'afyakit-api.firebaseapp.com',
    storageBucket: 'afyakit-api.firebasestorage.app',
  );

}